[common]
name = "Config Generator Development"
description = "This is a config for dev"
author = "JP"

[[services]]
#This is the app service.
hostname = "app"
image = "ubuntu:latest"
ports = [
    "8080:8080"
]
volumes = [
    "/host/app1:/var/app1",
    "/host/app2:/var/app2",
]
environment = { mykey = "myvalue" }
env_file = [
    "common",
    "database",
]
networks = ["mynetwork"]

[[services]]
#This is the app service.
hostname = "mysql"
image = "ubuntu:latest"
ports = [
    "3306:3306"
]
volumes = [
    "/db/data:/var/mysql/data",
]
environment = { username = "dbuser", password = "dbpassword" }
env_file = [
    "database",
]
networks = []

[[networks]]
name = "mynetwork"
driver = "bridge"
external = false

[[env_files]]
#Contains common environment variables
name = "common"
values = [
    { name = "myvar1", value = "1" },
    { name = "myvar2", value = "2" },
    { name = "myvar3", value = "myvalue3" },
]


[[env_files]]
#Contains database environment variables.
name = "database"
values = [
    { name = "DB_USERNAME", value = "root" },
    { name = "DB_PASSWORD", value = "thisisasecretdbpassword" },
    { name = "DB_HOST", value = "127.0.0.0" },
    { name = "DB_PORT", value = "3306" },
]
