[common]
name = "Config Generator Development"
description = "This is a config for dev"
author = "JP"

[[services]]
name = "app"
description = "This is the app service."
image = "myimage:latest"
ports = [
    ""
]
volumes = [
    "/host/app1:/var/app1",
    "/host/app2:/var/app2",
]
env_vars = [
    { name="mykey", value="value" }
]
env_files = [
    "/env/test1.env",
    "/env/test2.env",
]
repos = [
    { url = "", name = "app" }
]

[[env_files]]
name = "common"
description = "Contains common environment variables."
values = [
    { name = "myvar1", value = "myvalue1" },
    { name = "myvar2", value = "myvalue2" },
    { name = "myvar3", value = "myvalue3" },
]