[common]
name = "Config Generator Development"
description = "This is a config for dev"
author = "JP"

[[services]]
#This is the app service.
name = "app"
image = "myimage:latest"
ports = [
    ""
]
volumes = [
    "/host/app1:/var/app1",
    "/host/app2:/var/app2",
]
env_vars = [
    { name="mykey", value="value" }
]
env_files = [
    "/env/test1.env",
    "/env/test2.env",
]
repos = [
    { url = "", name = "app" }
]

[[env_files]]
#Contains common environment variables
name = "common"
values = [
    { name = "myvar1", value = "1" },
    { name = "myvar2", value = "2" },
    { name = "myvar3", value = "myvalue3" },
]


[[env_files]]
#Contains database environment variables.
name = "database"
values = [
    { name = "DB_USERNAME", value = "root" },
    { name = "DB_PASSWORD", value = "thisisasecretdbpassword" },
    { name = "DB_HOST", value = "127.0.0.0" },
    { name = "DB_PORT", value = "3306" },
]